apiVersion: v1
kind: Template
labels:
  template: openshift-activemq
message: A new persistent messaging service has been created in your project.
metadata:
  name: openshift-activemq
  creationTimestamp: null
  annotations:
    description: Application template for ActiveMQ. These can be deployed
      as standalone and use persistent storage for saving messages
    iconClass: icon-amq
    openshift.io/display-name: ActiveMQ 5.15.7
    openshift.io/provider-display-name: Mindbox
    tags: messaging,amq
    version: 5.15.7

parameters:
- name: NAMESPACE
  description: "OpenShift project (current namespace)"
  required: false
- name: ISTAG
  description: "Image to deploy"
  value: openshift-activemq
- name: ACTIVEMQ_USER
  description: "Username for the ActiveMQ instance"
  value: admin
- name: ACTIVEMQ_PASS
  description: "Password securing the ActiveMQ instance"
  generate: expression
  from: "[a-zA-Z0-9]{16}"
- name: VOLUME_SIZE
  description: "Size of the RabbitMQ data volume"
  value: 1Gi

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: openshift-activemq
      deploymentconfig: openshift-activemq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: openshift-activemq
          deploymentconfig: openshift-activemq
      spec:
        containers:
        - image: ''
          imagePullPolicy: Always
          name: openshift-activemq
          ports:
          - containerPort: 61616
            protocol: TCP
          - containerPort: 8161
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/amq
              name: activemq-config
            - mountPath: /tmp2
              name: activemq-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: activemq-config
        - emptyDir: {}
          name: activemq-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - openshift-activemq
        from:
          kind: ImageStreamTag
          name: openshift-activemq:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: openshift-activemq:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        //uri: https://github.com/MindboxGroup/openshift-activemq.git
        uri: https://github.com/devandtest/openshift-activemq.git
      type: Git
    strategy:
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: iC5AZ9ft5C5XgfrYkKQT
      type: GitHub
    - generic:
        secret: -z44GI1g-dXhvhWSGc5W
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    ports:
    - name: 8161-tcp
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: 61616-tcp
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      app: openshift-activemq
      deploymentconfig: openshift-activemq
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: openshift-activemq
    name: activemq
  spec:
    port:
      targetPort: 8161-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: openshift-activemq
      weight: 100
    wildcardPolicy: None
